#ifndef BETTER_C_STD_PRETTIFY_TERM_COLORS_H_
#define BETTER_C_STD_PRETTIFY_TERM_COLORS_H_

#define TERM_COLOR_GRAY "\033[90m"
#define TERM_COLOR_RED "\033[31m"
#define TERM_COLOR_BLUE "\033[34m"
#define TERM_COLOR_RESET "\033[0m"

#endif // BETTER_C_STD_PRETTIFY_TERM_COLORS_H_